name: "Starchain Go"
on:
  push:
      branches:
        - master

jobs:
  build:
    name: Starchain-Go
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        nix-shell -p go --pure --run 'go test ./...'
